# Generated by Django 2.1.4 on 2019-04-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='movie_actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='movie_genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_name',
        ),
    ]
