# Generated by Django 2.1.4 on 2019-04-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190414_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
