# Generated by Django 2.1.4 on 2019-04-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField()),
                ('movie_age_rating', models.CharField(max_length=100)),
                ('movie_duration_mins', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=100)),
                ('movie_directors', models.CharField(max_length=100)),
                ('movie_producers', models.CharField(max_length=100)),
                ('movie_writers', models.CharField(max_length=100)),
                ('imdb_movie_rating', models.CharField(max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_trailer_link', models.CharField(max_length=100)),
                ('movie_poster_1', models.ImageField(blank=True, upload_to='poster_1')),
                ('movie_poster_2', models.ImageField(blank=True, upload_to='poster_2')),
            ],
        ),
    ]
