# Generated by Django 2.1.1 on 2019-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_booking_history_theatre_ticket_price_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='now_playing',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='up_coming',
        ),
        migrations.RemoveField(
            model_name='ticket_price_and_time',
            name='theatre_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='booking_history',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='theatre',
        ),
        migrations.DeleteModel(
            name='ticket_price_and_time',
        ),
    ]
